#!/usr/bin/env python3
"""Compile sim/fixtures into a header the simulator links in.

The web build has no filesystem, so the captures cannot be read at runtime and
are baked into the binary instead. Everything here is generated: edit the JSON
under sim/fixtures or the manifest beside it, never sim/src/fixtures.h.

    tools/fixtures/bundle.py            write the header
    tools/fixtures/bundle.py --check    fail if it is out of date, for CI
"""

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FIXTURE_DIR = os.path.join(ROOT, "sim", "fixtures")
MANIFEST = os.path.join(FIXTURE_DIR, "manifest.json")
OUT = os.path.join(ROOT, "sim", "src", "fixtures.h")

HEADER = """#pragma once

// Generated by tools/fixtures/bundle.py from sim/fixtures. Do not edit.
//
// Real captures of the five sources, baked in because the web build has no
// filesystem to read them from. sim/fixtures/manifest.json says which URL each
// one answers, and tools/apicheck/check.py --save refreshes them from live.

#include <cstddef>
#include <cstdint>

namespace fixtures {

struct Route {
\tconst char *match;  // URL without the scheme, * matches any run
\tconst char *name;
\tconst char *body;
\tsize_t size;
};

"""

FOOTER = """
inline constexpr int COUNT = sizeof(ROUTES) / sizeof(ROUTES[0]);

}  // namespace fixtures
"""


def delimiter(body):
    """A raw string delimiter the body cannot possibly close."""
    for candidate in ("J", "JSON", "FIXTURE", "FIXTURE1", "FIXTURE2"):
        if ')%s"' % candidate not in body:
            return candidate
    raise SystemExit("no usable raw string delimiter")


def render():
    with open(MANIFEST) as handle:
        manifest = json.load(handle)

    blobs = []
    parts = [HEADER]
    total = 0
    rows = []
    for route in manifest["routes"]:
        name = route["fixture"]
        # A womp is a JPEG, and the panel decodes it from the stream, so the
        # simulator has to hand over the same bytes rather than a description
        # of them.
        binary = route.get("binary", False)
        path = os.path.join(FIXTURE_DIR, name + (".jpg" if binary else ".json"))
        if not os.path.exists(path):
            raise SystemExit("%s is in the manifest but %s does not exist. Run "
                             "tools/apicheck/check.py --save." % (name, os.path.relpath(path, ROOT)))

        if binary:
            with open(path, "rb") as handle:
                blob = handle.read()
            size = len(blob)
            symbol = "BLOB_%s" % name.replace("-", "_").upper()
            body = ["inline constexpr uint8_t %s[] = {\n" % symbol]
            for i in range(0, size, 16):
                body.append("    " + ", ".join("0x%02x" % b for b in blob[i:i + 16]) + ",\n")
            body.append("};\n\n")
            blobs.append("".join(body))
            rows.append('\t{"%s", "%s",\n\t (const char *)%s,\n\t %d},\n'
                        % (route["match"], name, symbol, size))
        else:
            with open(path) as handle:
                body = handle.read().strip()
            json.loads(body)  # a fixture that is not JSON is a bug, not a payload
            # Size is in bytes, not characters. A payload with any non ASCII in
            # it is longer than it looks, and a short count truncates the parse.
            size = len(body.encode("utf-8"))
            mark = delimiter(body)
            rows.append('\t{"%s", "%s",\n\t R"%s(%s)%s",\n\t %d},\n'
                        % (route["match"], name, mark, body, mark, size))
        total += size

    parts += blobs
    # const rather than constexpr: a JPEG blob is a byte array and the cast to
    # char is not a constant expression. The table still lands in flash.
    parts.append("inline const Route ROUTES[] = {\n")
    parts += rows
    parts.append("};\n")
    parts.append(FOOTER)
    return "".join(parts), len(manifest["routes"]), total


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="exit non zero when the header does not match the fixtures")
    args = parser.parse_args()

    text, routes, total = render()
    current = ""
    if os.path.exists(OUT):
        with open(OUT) as handle:
            current = handle.read()

    if args.check:
        if current != text:
            print("sim/src/fixtures.h is stale. Run tools/fixtures/bundle.py.")
            return 1
        print("sim/src/fixtures.h matches the %d fixtures in sim/fixtures" % routes)
        return 0

    if current == text:
        print("sim/src/fixtures.h already matches the %d fixtures" % routes)
        return 0
    with open(OUT, "w") as handle:
        handle.write(text)
    print("wrote %s, %d routes, %.1fKB of captured payload"
          % (os.path.relpath(OUT, ROOT), routes, total / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
