#!/usr/bin/env python3
"""Turn Lucide icons into a 1 bit atlas the firmware can draw.

Same rule as the glyph atlas: generated, never hand edited. Run this, commit
both the tool and src/icons.h.

    python3 tools/icons/generate.py

An app pack lives in another repository and cannot add a row to the atlas, so
it generates a header of its own with the same tool and the same bitmap format,
and points view::View::art at it:

    python3 tools/icons/generate.py \\
        --pack anchor:ANCHOR:32 --namespace anchorart --out ../app/src/art.h

Lucide is ISC licensed. The notice travels with the generated header.
"""

import argparse
import pathlib
import subprocess
import sys
import urllib.request

RAW = "https://unpkg.com/lucide-static@1.32.0/icons/{}.svg"
OUT = pathlib.Path(__file__).resolve().parents[2] / "src" / "icons.h"
CACHE = pathlib.Path(__file__).resolve().parent / "svg"

# Lucide name, enum name, pixel size. Lucide draws on a 24px grid with a 2px
# stroke; shrinking that leaves a stroke under half a pixel in places, so the
# stroke is widened before rasterizing rather than after. The menu draws at 32,
# which is above the source grid and needs no widening at all; the three drawn
# inside Setup stay at 12.
ICONS = [
    ("waves", "WAVES", 32),
    ("landmark", "LANDMARK", 32),
    ("bot", "BOT", 32),
    ("camera", "CAMERA", 32),
    ("fuel", "FUEL", 32),
    ("settings", "SETTINGS", 32),
    ("music", "MUSIC", 32),
    ("wind", "WIND", 32),
    ("cloud-rain", "CLOUD_RAIN", 32),
    ("route", "ROUTE", 32),
    ("wifi", "WIFI", 12),
    ("keyboard", "KEYBOARD", 12),
    ("trash-2", "TRASH", 12),
]
STROKE = {32: "2.0", 16: "2.6", 12: "3.0"}

LICENSE = """// Lucide is ISC licensed:
//   Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as
//   part of Feather (MIT). All other copyright (c) for Lucide are held by
//   Lucide Contributors 2022.
//
// Each icon is one bit per pixel, row major, MSB first, rows padded to a byte,
// which is what M5GFX's drawBitmap takes."""


def fetch(name):
    CACHE.mkdir(exist_ok=True)
    path = CACHE / f"{name}.svg"
    if not path.exists():
        with urllib.request.urlopen(RAW.format(name), timeout=30) as response:
            path.write_bytes(response.read())
    return path


def rasterize(path, size):
    svg = path.read_text()
    svg = svg.replace('stroke-width="2"', f'stroke-width="{STROKE[size]}"')
    wide = path.with_suffix(".wide.svg")
    wide.write_text(svg)
    png = path.with_suffix(f".{size}.png")
    subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size), "-o", str(png), str(wide)],
        check=True,
    )
    out = subprocess.run(
        ["magick", str(png), "-alpha", "extract", "-depth", "8", "gray:-"],
        check=True, capture_output=True,
    ).stdout
    return [[1 if out[y * size + x] >= 110 else 0 for x in range(size)] for y in range(size)]


def pack(rows, size):
    """Row major, MSB first, each row starting on a byte boundary."""
    stride = (size + 7) // 8
    data = []
    for row in rows:
        for byte in range(stride):
            value = 0
            for bit in range(8):
                x = byte * 8 + bit
                if x < size and row[x]:
                    value |= 0x80 >> bit
            data.append(value)
    return data


def draw(icons):
    """Rasterize each icon, returning the bitmap literal and the preview."""
    lines = []
    preview = []
    for name, enum, size in icons:
        rows = rasterize(fetch(name), size)
        preview.append((name, rows))
        data = pack(rows, size)
        body = ", ".join(f"0x{b:02x}" for b in data)
        lines.append(f"// {name}, {size}x{size}\nconstexpr uint8_t {enum}_DATA[] = {{{body}}};")
    return lines, preview


def atlas(icons):
    """The firmware's own header: an enum, the bitmaps, and a table."""
    lines, preview = draw(icons)
    entries = "\n".join(
        f"\t{{{enum}_DATA, {size}, {size}}},  // {name}" for name, enum, size in icons
    )
    names = "\n".join(f"\t{enum}," for _, enum, _ in icons)
    OUT.write_text(f'''#pragma once

// Generated by tools/icons/generate.py from Lucide. Do not edit by hand.
//
{LICENSE}

#include <cstdint>

namespace icons {{

enum Id : uint8_t {{
{names}
\tCOUNT,
}};

struct Icon {{
\tconst uint8_t *data;
\tint width;
\tint height;
}};

{chr(10).join(lines)}

constexpr Icon ALL[] = {{
{entries}
}};

}}  // namespace icons
''')
    return preview, OUT


def pack_header(icons, namespace, out):
    """An app pack's header: the same bitmaps, as icons::Icon values.

    No enum and no table, because an app pack's art is never indexed by id. A
    view points its `art` field straight at one of these.
    """
    lines, preview = draw(icons)
    values = "\n".join(
        f"constexpr icons::Icon {enum} = {{{enum}_DATA, {size}, {size}}};"
        for _, enum, size in icons
    )
    out = pathlib.Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(f'''#pragma once

// Generated by flint's tools/icons/generate.py from Lucide. Do not edit by hand.
//
{LICENSE}
//
// Regenerate with:
//   python3 tools/icons/generate.py --pack {" --pack ".join(f"{n}:{e}:{s}" for n, e, s in icons)} \\
//       --namespace {namespace} --out <this file>

#include <cstdint>

#include "icons.h"

namespace {namespace} {{

{chr(10).join(lines)}

{values}

}}  // namespace {namespace}
''')
    return preview, out


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--pack", action="append", metavar="LUCIDE:NAME:SIZE",
        help="one icon for an app pack header, rather than the firmware atlas",
    )
    parser.add_argument("--namespace", default="art", help="namespace for a pack header")
    parser.add_argument("--out", help="where a pack header is written")
    args = parser.parse_args()

    if args.pack:
        if not args.out:
            parser.error("--pack needs --out")
        icons = []
        for spec in args.pack:
            parts = spec.split(":")
            if len(parts) != 3:
                parser.error(f"--pack wants LUCIDE:NAME:SIZE, got {spec}")
            size = int(parts[2])
            if size not in STROKE:
                parser.error(f"no stroke width for {size}px, add one to STROKE")
            icons.append((parts[0], parts[1], size))
        preview, written = pack_header(icons, args.namespace, args.out)
    else:
        preview, written = atlas(ICONS)

    for name, rows in preview:
        print(f"\n{name}")
        for row in rows:
            print("  " + "".join("#" if v else "." for v in row))
    print(f"\nwrote {written}")


if __name__ == "__main__":
    sys.exit(main())
